### ISSUE TITLE
RuntimeError in ParamDefinition.php#L251

### ISSUE THREAD

**Issue by s7eph4n** [JeroenDeDauw/ParamProcessor#12]
https://github.com/JeroenDeDauw/ParamProcessor/blob/master/src/ParamDefinition.php#L251 will trigger a RuntimeError if `validator` is not set (e.g. for the Excel format up until SRF 2.3).

If on the other hand it is considered as given that `validator` is set (e.g. because using the ParamDefinitionFactory is mandatory) then testing `$this->validator !== null` in line 253 is pointless.

No patch, sorry. Don't know, what the correct solution should be. Use `getValidator()` instead of directly accessing the variable?

**Comment by JeroenDeDauw** [comment]
Gah, this code is so shitty... Should be fixed by 5e411430550160dddec460aab1aa25f9b5473281

**Comment by JeroenDeDauw** [comment]
I've created a new patch release
