### ISSUE TITLE
PHP Notice:  Undefined index: original-value

### ISSUE THREAD

**Issue by mwjames** [JeroenDeDauw/ParamProcessor#36]
param-processor/param-processor: 1.3.4

PHP log has reports of:

```
PHP Notice:  Undefined index: original-value in ...\vendor\param-processor\param-processor\src\Processor.php on line 235
```

**Comment by JeroenDeDauw** [comment]
Not enough info to tell if this issue is wit ParamProcessor or the caller.

**Comment by JeroenDeDauw** [comment]
Oops. Why is the "Close and comment" button so close to the "Comment" one :)

**Comment by JeroenDeDauw** [comment]
Please reopen or create new issue if this still shows up in some log with a recent version.
